import type {Metadata} from 'next';
import {Inter} from 'next/font/google';
import './globals.css';
import Link from 'next/link';
import {Avatar, AvatarFallback, AvatarImage} from '@/components/ui/avatar';

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
});

export const metadata: Metadata = {
  title: 'Firebase Studio App',
  description: 'Generated by Firebase Studio',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} font-sans antialiased`}>
        <div className="relative">
          <div className="absolute top-4 right-4">
            <Link href="/profile">
              <Avatar>
                <AvatarImage src="https://picsum.photos/id/88/50/50" alt="User Avatar" />
                <AvatarFallback>U</AvatarFallback>
              </Avatar>
            </Link>
          </div>
          {children}
        </div>
      </body>
    </html>
  );
}


