import type {Metadata} from 'next';
import {Geist, Geist_Mono} from 'next/font/google';
import './globals.css';
import Link from 'next/link';
import {Avatar, AvatarFallback, AvatarImage} from '@/components/ui/avatar';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Firebase Studio App',
  description: 'Generated by Firebase Studio',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="relative">
          <div className="absolute top-4 right-4">
            <Link href="/profile">
              <Avatar>
                <AvatarImage src="https://picsum.photos/id/88/50/50" alt="User Avatar" />
                <AvatarFallback>U</AvatarFallback>
              </Avatar>
            </Link>
          </div>
          {children}
        </div>
      </body>
    </html>
  );
}

